---
  - name: Stop MQ Server
    service:
      name: ctrl_mq_server
      state: stopped
      
  - name: Check MQ Server is still running
    shell: "ps -ef | grep [r]unmqlsr"
    register: mq_started
    ignore_errors: yes

  - name: Debug MQ process check
    debug:
      var: mq_started 

  - name: Stop MQ manually
    shell: /etc/init.d/ctrl_mq_server stop
    when: mq_started.rc == 0
